#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Se placer dans la racine Git du projet (peu importe où on lance la commande)
cd "$(git rev-parse --show-toplevel)" || exit 1

# Maintenant tu peux faire tes commandes
cd frontend || exit 1
npm run format
npm run lint

cd ../backend || exit 1
mvn spotless:apply pmd:check spotbugs:check